name: CI/CD Pipeline for MLOPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build Docker image
      - name: Build the Docker image
        run: docker build -t mlops-app ./MLOPS

      # Step 4: Test the Docker container
      - name: Run the container for testing
        run: |
          docker run -d -p 5000:5000 --name mlops-container mlops-app
          sleep 10  # wait for the container to start

      # Step 5: Test the Flask app
      - name: Test Flask API
        run: curl --fail http://localhost:5000/predict -d '{"text": "I am happy"}' -H "Content-Type: application/json"

      # Step 6: Clean up
      - name: Stop and remove the container
        run: |
          docker stop mlops-container
          docker rm mlops-container
